spring:
  datasource:
    url: jdbc:mariadb://@DB_URL@/@DB_NAME@
    username: @DB_USER@
    password: @DB_PW@
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: @DB_HIBERNATE_INIT@
    database: mysql
    defer-datasource-initialization: @DB_DATASOURCE_INIT@
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: @DB_SHOW_SQL@
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      platform: @DB_INIT_FILE@
      mode: @DB_INIT_MODE@
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /
  port: 8080

jwt:
  secret: @JWT_SECRET@

cors:
  domain: @CORS_DOMAIN@
