spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    url: jdbc:mariadb://51.178.28.219:3306/discord
    username: web
    password: web
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      platform: mysql
      mode: always

server:
  servlet:
    context-path: /alert-mns
